import type { Metadata } from "next";
import Link from "next/link";
import { ContactCTA } from "../components/ContactCTA";
import { PageHero } from "../components/PageHero";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";

export const metadata: Metadata = { title: "Storing en service | Rob Braam", description: "Servicevragen en storingen voor cv-ketels en warmtepompen. Bel 073 622 2199 of mail service@robbraam.com." };

export default function ServicePage() {
  return <><SiteHeader /><main>
    <PageHero eyebrow="Storing & service" title="Is er iets met uw installatie?" accent="Laat ons weten wat u ziet." intro="U hoeft zelf niet uit te zoeken wat er precies defect is. Stuur ons het merk, type, de storingscode en een paar duidelijke foto’s. Daarmee kan iemand uit ons serviceteam uw vraag sneller beoordelen." image="/about/planning-rob-braam.jpg" imageAlt="Telefonisch contact met Rob Braam" primaryLabel="Mail ons serviceteam" primaryHref="mailto:service@robbraam.com?subject=Servicevraag" badge="Rechtstreeks naar service" />
    <section className="section service-contact-section reveal"><div className="shell"><div className="section-heading centered-heading"><p className="eyebrow"><span /> Kies wat bij uw vraag past</p><h2>Zo komt u bij de juiste collega terecht.</h2></div><div className="service-contact-grid"><a href="tel:+31736222199"><span className="service-contact-icon">!</span><small>Een storing die niet kan wachten</small><strong>Bel 073 622 2199</strong><p>Houd merk, type en de storingscode bij de hand als dat lukt.</p><b>Bel ons →</b></a><a href="mailto:service@robbraam.com?subject=Aanvraag%20werk%20of%20servicevraag"><span className="service-contact-icon">S</span><small>Aanvraag, storing of technische vraag</small><strong>service@robbraam.com</strong><p>Stuur uw adres, telefoonnummer, merk, type, foutcode of omschrijving en duidelijke foto&apos;s mee. Ook aanvragen voor werk gaan via service.</p><b>Mail ons serviceteam →</b></a><a href="mailto:planning@robbraam.com?subject=Afspraak%20plannen%20of%20wijzigen"><span className="service-contact-icon">P</span><small>Afspraak plannen of wijzigen</small><strong>planning@robbraam.com</strong><p>Voor het plannen, verzetten of annuleren van een afspraak nadat uw aanvraag is afgestemd.</p><b>Mail onze planning →</b></a></div><p className="service-subscription-link">Een abonnement vergelijken? <Link href="/onderhoud">Bekijk onderhoud en abonnementen <span aria-hidden="true">→</span></Link></p></div></section>

    <section className="dark-story reveal"><div className="shell dark-story-grid"><div><p className="eyebrow eyebrow-light"><span /> Veilig handelen</p><h2>Ruikt u gas of vermoedt u koolmonoxide?</h2></div><div><p>Neem geen risico. Vermijd vonken en open vuur en ga naar buiten als dat veilig kan. Ruikt u gas? Bel gratis het Nationaal Storingsnummer gas en stroom op <strong>0800 9009</strong>. Dit nummer is dag en nacht bereikbaar. Bij direct gevaar belt u 112.</p><div className="emergency-actions"><a className="button button-primary" href="tel:08009009">Gaslucht: bel 0800 9009 <span aria-hidden="true">↗</span></a><a className="certificate-link" href="tel:112">Direct gevaar: bel 112 <span aria-hidden="true">↗</span></a></div></div></div></section>

    <section className="section service-prep reveal"><div className="shell service-prep-grid"><div><p className="eyebrow"><span /> Hiermee kunnen we sneller beginnen</p><h2>Drie dingen die we graag ontvangen.</h2></div><ol><li><span>01</span><div><strong>Uw adres en telefoonnummer</strong><p>Dan weten we om welke installatie het gaat en hoe we u kunnen bereiken.</p></div></li><li><span>02</span><div><strong>Merk, type en storingscode</strong><p>Deze gegevens staan meestal op het toestel of in het display.</p></div></li><li><span>03</span><div><strong>Foto&apos;s van het toestel en de situatie</strong><p>Een overzichtsfoto en een close-up van het display of de lekkage helpen ons bij de eerste beoordeling.</p></div></li></ol></div></section>
    <ContactCTA title="Wilt u een servicevraag doorgeven?" text="Mail naar service@robbraam.com. Voor een storing die niet kan wachten kunt u ons bellen op 073 622 2199." />
  </main><SiteFooter /></>;
}
