import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";

export const metadata: Metadata = { title: "Contact | Rob Braam", description: "Contact met Rob Braam voor offerte, onderhoud, service of planning. Bel 073 622 2199 of mail de juiste afdeling." };

export default function ContactPage() {
  return <><SiteHeader /><main>
    <section className="contact-page-hero"><div className="shell"><div className="breadcrumb breadcrumb-dark"><Link href="/">Home</Link><span>/</span><strong>Contact</strong></div><div className="contact-page-heading"><div><p className="eyebrow eyebrow-light"><span /> Neem rechtstreeks contact op</p><h1>Vertel ons waarmee<br /><em>we u kunnen helpen.</em></h1></div><p>Uw bericht komt bij ons eigen team terecht. Werk, offertes, storingen en technische vragen gaan via service. Planning is bedoeld voor onderhoud en het plannen, verzetten of annuleren van afspraken.</p></div></div></section>
    <section className="contact-route-section" id="contact-keuze"><div className="shell"><div className="contact-route-grid"><a className="route-service" href="mailto:service@robbraam.com?subject=Aanvraag%20werk%20of%20servicevraag"><span className="route-index">01</span><small>Werk · offerte · storing · technische vraag</small><h2>Service</h2><strong>service@robbraam.com</strong><p>Voor een nieuwe installatie, offerte, storing, technische vraag of inhoudelijke vraag over uw installatie.</p><b>Mail ons serviceteam <i>↗</i></b></a><a href="mailto:planning@robbraam.com?subject=Onderhoud%20of%20afspraak"><span className="route-index">02</span><small>Onderhoud · afspraak plannen · wijzigen</small><h2>Planning</h2><strong>planning@robbraam.com</strong><p>Voor onderhoud, een onderhoudsafspraak plannen, een afspraak verzetten of annuleren en vragen over de onderhoudsplanning.</p><b>Mail onze planning <i>↗</i></b></a></div><div className="contact-form-route"><div><span>Nieuwe installatie of advies</span><strong>Beantwoord een paar korte vragen of laat ons terugbellen.</strong><p>Dan komt uw aanvraag met de juiste informatie bij het juiste team binnen.</p></div><div className="contact-form-actions"><Link className="button button-primary" href="/offerte-aanvragen">Start een offerteaanvraag <span aria-hidden="true">→</span></Link><Link className="text-link" href="/bel-mij-terug">Laat mij terugbellen <span aria-hidden="true">→</span></Link></div></div></div></section>
    <section className="section contact-details reveal"><div className="shell contact-details-grid"><div><p className="eyebrow"><span /> Liever even bellen?</p><h2>U krijgt gewoon iemand<br />van Braam aan de lijn.</h2><a className="large-phone" href="tel:+31736222199">073 622 2199</a><p>Jacob van Wassenaerstraat 10<br />5224 GG &apos;s-Hertogenbosch</p><small>Wilt u langskomen? Onze ontvangstruimte is op afspraak geopend.</small></div><figure><img src="/about/bedrijfspand-braam.webp" alt="Bedrijfspand van Rob Braam in 's-Hertogenbosch" /><figcaption><i /> Service & Montagebedrijf Rob Braam</figcaption></figure></div></section>
    <section className="section region-list-section reveal"><div className="shell region-list-grid"><div><p className="eyebrow"><span /> Werkgebied</p><h2>Vanuit &apos;s-Hertogenbosch<br />actief in een brede regio.</h2><p>Ons meeste onderhoud zit in &apos;s-Hertogenbosch en omgeving. We werken daarnaast op veel adressen in Noord-Brabant en in aangrenzende delen van Gelderland. De plaatsen hiernaast zijn voorbeelden en vormen geen vaste grens.</p></div><div className="place-list"><span>&apos;s-Hertogenbosch</span><span>Hedel</span><span>Ammerzoden</span><span>Tilburg</span><span>Vlijmen</span><span>Berlicum</span><span>Vught</span><span>Rosmalen</span><strong>Uw plaats staat er niet bij? Stuur uw postcode en het soort werkzaamheden door, dan laten we weten wat mogelijk is.</strong></div></div></section>
  </main><SiteFooter /></>;
}
