import type { Metadata } from "next";
import { ContactCTA } from "../components/ContactCTA";
import { MobileActionBar } from "../components/MobileActionBar";
import { PageHero } from "../components/PageHero";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";

export const metadata: Metadata = { title: "Airco installeren in de regio | Rob Braam", description: "Advies, installatie en service voor energiezuinige airconditioning vanuit 's-Hertogenbosch, in Noord-Brabant en aangrenzende delen van Gelderland." };

export default function AircoPage() {
  return <><SiteHeader /><main>
    <PageHero eyebrow="Airconditioning" title="Airco voor de ruimte die u gebruikt." accent="Goed berekend en netjes geplaatst." intro="Wilt u een slaapkamer koel houden, een kantoor comfortabel maken of één leefruimte gericht verwarmen? We bekijken de ruimte en adviseren een systeem dat daarbij past." image="/projects/warmtepomp-vlijmen.jpg" imageAlt="Buitenunit van een installatie van Rob Braam" primaryLabel="Bespreek uw airco" primaryHref="/offerte-aanvragen?dienst=airco" badge="Koelen én verwarmen" />
    <section className="section detail-intro reveal"><div className="shell detail-intro-grid"><div><p className="eyebrow"><span /> Eerst kijken naar de ruimte</p><h2>We bepalen wat nodig is.<br />Niet wat het grootste is.</h2></div><div><p>De juiste capaciteit maakt een airco stiller, zuiniger en prettiger in gebruik. Daarom letten we op de grootte en ligging van de ruimte, de zon, de gewenste temperatuur en een nette route voor de leidingen.</p><ul className="check-list"><li>Voor woning, slaapkamer, kantoor of bedrijfspand</li><li>Single-split en multi-split mogelijk</li><li>Koelen en gericht verwarmen met één systeem</li><li>Installatie door STEK-gecertificeerde vakmensen</li></ul></div></div></section>
    <section className="section option-section reveal"><div className="shell"><div className="section-heading centered-heading"><p className="eyebrow"><span /> Hier letten we op</p><h2>Vier onderdelen van een goede installatie.</h2></div><div className="benefit-grid"><article><span>01</span><h3>Passend vermogen</h3><p>We stemmen het vermogen af op de ruimte, zonbelasting en de manier waarop u de airco wilt gebruiken.</p></article><article><span>02</span><h3>Een rustige plek</h3><p>We zoeken een positie met goede luchtverdeling, zo min mogelijk geluid en een nette leidingroute.</p></article><article><span>03</span><h3>De juiste voeding</h3><p>Is een aparte groep nodig? Dan kan onze eigen elektricien dat direct in het werk meenemen.</p></article><article><span>04</span><h3>Uitleg en service</h3><p>Na de montage leggen we de bediening uit. Heeft u later een vraag, dan kunt u gewoon weer bij ons terecht.</p></article></div></div></section>
    <section className="dark-story reveal"><div className="shell dark-story-grid"><div><p className="eyebrow eyebrow-light"><span /> Koelen én verwarmen</p><h2>Een airco kan ook gericht verwarmen.</h2></div><div><p>Een moderne airco is technisch een lucht-luchtwarmtepomp. Daarmee kunt u bijvoorbeeld een werkkamer of leefruimte snel verwarmen zonder meteen de hele woning op temperatuur te brengen. We leggen graag uit wanneer dat wel en niet handig is.</p><a className="certificate-link" href="/offerte-aanvragen?dienst=airco">Vertel ons om welke ruimtes het gaat <span>↗</span></a></div></div></section>
    <ContactCTA title="Welke ruimte wilt u koelen of verwarmen?" text="Stuur ons het aantal ruimtes en een korte omschrijving. We nemen persoonlijk contact op om capaciteit, plaatsing en mogelijkheden te bespreken." primaryLabel="Vraag aircoadvies aan" primaryHref="/offerte-aanvragen?dienst=airco" />
  </main><MobileActionBar href="/offerte-aanvragen?dienst=airco" label="Bespreek uw airco" /><SiteFooter /></>;
}
