import type { Metadata } from "next";
import { ContactCTA } from "../components/ContactCTA";
import { PageHero } from "../components/PageHero";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";

export const metadata: Metadata = { title: "Over Service & Montagebedrijf Rob Braam", description: "Gecertificeerd installatiebedrijf uit 's-Hertogenbosch, opgericht in 2000. Advies, installatie, onderhoud en service onder één dak." };

export default function OverOnsPage() {
  return <><SiteHeader /><main>
    <PageHero eyebrow="Over Braam" title="Sinds 2000 een vertrouwd bedrijf." accent="In ’s-Hertogenbosch en omgeving." intro="Service & Montagebedrijf Rob Braam is sinds 2000 actief vanuit ’s-Hertogenbosch. We werken in Noord-Brabant en aangrenzende delen van Gelderland, met persoonlijk contact voor en na de oplevering." image="/about/team-rob-braam.jpg" imageAlt="Monteurs van Service & Montagebedrijf Rob Braam" primaryLabel="Neem contact met ons op" badge="Ons eigen team in ’s-Hertogenbosch" />
    <section className="section detail-intro reveal"><div className="shell detail-intro-grid"><div><p className="eyebrow"><span /> Groei in de regio</p><h2>Dichtbij begonnen.<br />Steeds breder actief.</h2></div><div><p>Ons meeste onderhoud zit in &apos;s-Hertogenbosch en omgeving. Inmiddels werken we ook op veel adressen verder in Noord-Brabant en in aangrenzende delen van Gelderland. Bij een nieuwe aanvraag controleren we postcode, installatie en werkzaamheden, zodat u vooraf weet wat op uw adres mogelijk is.</p><ul className="check-list"><li>U spreekt rechtstreeks met ons eigen team</li><li>Gecertificeerde vakmensen voor iedere discipline</li><li>Installatie en elektra onder één dak</li><li>Onderhoud en service na de oplevering</li></ul></div></div></section>
    <section className="image-story reveal"><div className="shell image-story-grid"><figure><img src="/about/ontvangstruimte-braam.png" alt="Ontvangstruimte van Rob Braam" /><figcaption>Persoonlijk afspreken in &apos;s-Hertogenbosch</figcaption></figure><div><p className="eyebrow"><span /> Eerst luisteren</p><h2>We nemen de tijd om uw situatie te begrijpen.</h2><p>Sommige vragen zijn snel telefonisch te beantwoorden. Voor een groter plan kunnen we bij u thuis kijken of u op afspraak ontvangen in &apos;s-Hertogenbosch. We leggen de techniek in normale taal uit en maken duidelijk wat wel en niet nodig is.</p><div className="story-points"><div><strong>01</strong><span>Uw wensen en woning leren kennen</span></div><div><strong>02</strong><span>Mogelijkheden begrijpelijk uitleggen</span></div><div><strong>03</strong><span>Duidelijk afspreken wie wat doet</span></div></div></div></div></section>
    <section className="section values-section reveal"><div className="shell"><div className="section-heading centered-heading"><p className="eyebrow"><span /> Wat u van ons mag verwachten</p><h2>Zo willen we met klanten werken.</h2></div><div className="benefit-grid"><article><span>01</span><h3>Een eerlijk antwoord</h3><p>We adviseren wat technisch en praktisch bij uw woning past, ook als een andere oplossing verstandiger is.</p></article><article><span>02</span><h3>Netjes werk</h3><p>Een installatie moet goed functioneren, verzorgd zijn aangelegd en later bereikbaar blijven voor onderhoud.</p></article><article><span>03</span><h3>Veilige vakmensen</h3><p>Ons bedrijf en onze monteurs hebben de certificeringen en vakbekwaamheid die voor hun werk nodig zijn.</p></article><article><span>04</span><h3>Contact na afloop</h3><p>Na de oplevering kunt u bij hetzelfde bedrijf terecht voor onderhoud, een servicevraag of gewoon uitleg.</p></article></div></div></section>
    <ContactCTA title="Wilt u weten of Braam bij u past?" text="Vertel ons eerst waar u hulp bij zoekt. We beoordelen uw vraag en laten weten of foto&apos;s en gegevens voldoende zijn of dat een afspraak op locatie nodig is. In &apos;s-Hertogenbosch ontvangen we u op afspraak." />
  </main><SiteFooter /></>;
}
