import type { Metadata } from "next";
import Link from "next/link";
import { ContactCTA } from "../components/ContactCTA";
import { MobileActionBar } from "../components/MobileActionBar";
import { PageHero } from "../components/PageHero";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";

export const metadata: Metadata = { title: "Warmtepomp voor uw woning | Rob Braam", description: "Advies, installatie en onderhoud van warmtepompen van 7, 9 en 11 kW voor woningen, met LG en Vaillant als vaste merken." };

export default function WarmtepompenPage() {
  return <><SiteHeader /><main>
    <PageHero eyebrow="Warmtepompen voor woningen" title="Een warmtepomp die bij uw woning past." accent="Begint met een goede beoordeling." intro="Wij werken met warmtepompen van 7, 9 en 11 kW. Welk vermogen geschikt is, bepalen we vooral aan de hand van het warmteverlies, de isolatie en de warmteafgifte via radiatoren of vloerverwarming. Na uw aanvraag laten we weten welke vervolgstap nodig is." image="/projects/warmtepomp-berlicum.jpg" imageAlt="Vaillant warmtepomp geplaatst door Rob Braam in Berlicum" primaryLabel="Vraag naar de mogelijkheden" primaryHref="/offerte-aanvragen?dienst=warmtepomp" badge="LG & Vaillant" />

    <section className="section detail-intro reveal"><div className="shell detail-intro-grid"><div><p className="eyebrow"><span /> Van aanvraag naar advies</p><h2>Eerst beoordelen.<br />Dan gericht opnemen.</h2></div><div><p>Na uw aanvraag bekijken we eerst de omschrijving, foto&apos;s en gegevens van de bestaande installatie. Als een technische opname nodig is, plannen we daarvoor een afspraak op locatie. Tijdens die opname verzamelen we de gegevens voor de warmteverliesberekening en brengen we het afgiftesysteem, de mogelijke plaats van de buitenunit en de elektrische aansluiting in kaart. Daarna ontvangt u een advies en offerte.</p><ul className="check-list"><li>Eerst beoordeling van uw aanvraag</li><li>Technische opname wanneer dat nodig is</li><li>Ervaring met LG en Vaillant</li><li>Eigen elektricien voor de aansluiting</li></ul></div></div></section>

    <section className="section option-section reveal"><div className="shell"><div className="section-heading centered-heading"><p className="eyebrow"><span /> Hybride of volledig elektrisch</p><h2>We leggen het verschil gewoon uit.</h2></div><div className="heat-pump-scope"><strong>7, 9 en 11 kW</strong><p>Wij werken met warmtepompen van 7, 9 en 11 kW voor woningen. Grote bedrijfsunits, cascadeopstellingen en collectieve systemen vallen buiten onze werkzaamheden.</p></div><div className="option-grid">
      <article><span className="option-index">01</span><h3>Hybride warmtepomp</h3><p>De warmtepomp verwarmt zoveel mogelijk elektrisch. Op koude momenten en voor warm tapwater helpt de cv-ketel mee.</p><ul><li>Vaak mogelijk in een bestaande woning</li><li>Minder gas gebruiken zonder direct volledig van het gas af te gaan</li><li>Onderhoud voor ketel en warmtepomp samen mogelijk</li></ul><Link href="/offerte-aanvragen?dienst=warmtepomp">Vraag naar de mogelijkheden <span>→</span></Link></article>
      <article className="option-featured"><span className="option-index">02</span><h3>Volledig elektrische warmtepomp</h3><p>Dit wordt ook wel full-electric genoemd. De warmtepomp verzorgt de verwarming en het warme water, zonder hulp van een cv-ketel.</p><ul><li>Geen cv-ketel nodig voor verwarming</li><li>Warm tapwater via een boilervat</li><li>Comfort vanaf € 19,92 per maand; jaarprijs € 239.</li></ul><Link href="/onderhoud">Lees over het onderhoud <span>→</span></Link></article>
    </div></div></section>

    <section className="section manufacturer-info reveal"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow"><span /> LG en Vaillant uitgelegd</p><h2>Twee vaste merken.<br />Verschillende opstellingen.</h2></div><p>Voor installatie en onderhoud werken we standaard met LG en Vaillant. Heeft u al een warmtepomp van een ander merk? Stuur merk en model mee; onderhoud aan andere merken beoordelen we op aanvraag.</p></div><div className="manufacturer-grid"><article><span>LG THERMA V</span><h3>Hoge aanvoertemperatuur en verschillende binnenopstellingen.</h3><p>De LG THERMA V R290 Monobloc is een lucht-waterwarmtepomp voor de verwarming van de woning. LG vermeldt een watertemperatuur tot 75 °C en biedt verschillende combinaties met binnendelen. Met een passende combi-unit kunnen onder meer een warmwatervat, elektrische bijverwarming en een expansievat in de binnenopstelling worden opgenomen.</p><p>De hogere mogelijke watertemperatuur kan mogelijkheden bieden bij bestaande radiatoren. Dat betekent niet dat iedere woning zonder aanpassingen geschikt is: het benodigde vermogen en de gewenste aanvoertemperatuur moeten eerst worden berekend.</p><ul><li>Verwarming via radiatoren of vloerverwarming, afhankelijk van de woning</li><li>Warm tapwater met een passende binnenopstelling en voorraadvat</li><li>Technische opname voor capaciteit, plaatsing en elektrische aansluiting</li></ul><a href="https://www.lg.com/nl/warmtepomp/therma-v-r290-monobloc/" target="_blank" rel="noreferrer">Bekijk de units van LG <span aria-hidden="true">↗</span></a></article><article><span>Vaillant aroTHERM plus</span><h3>Verwarming, warm water en koeling in één systeem.</h3><p>Vaillant beschrijft de aroTHERM plus als een lucht-waterwarmtepomp voor verwarming, warm water en koeling. Het systeem werkt met het natuurlijke koudemiddel R290, kan water tot 75 °C leveren en kan worden toegepast met vloerverwarming of radiatoren.</p><p>Voor warm tapwater kan de buitenunit worden gecombineerd met een passend binnendeel, zoals de uniTOWER met geïntegreerd voorraadvat. Welke functies, capaciteit en binnenopstelling nodig zijn, hangt af van uw woning en gebruik.</p><ul><li>Verwarming via radiatoren of vloerverwarming, afhankelijk van de woning</li><li>Warm tapwater en koeling met een daarvoor geschikte systeemopbouw</li><li>Technische opname voor capaciteit, plaatsing en elektrische aansluiting</li></ul><a href="https://www.vaillant.nl/producten/arothermplus/" target="_blank" rel="noreferrer">Bekijk de units van Vaillant <span aria-hidden="true">↗</span></a></article></div><p className="manufacturer-note">De genoemde mogelijkheden komen uit de productinformatie van LG en Vaillant. Welke uitvoering, functies en aanpassingen voor uw woning worden aangeboden, staat pas vast in onze offerte.</p></div></section>

    <section className="image-story reveal"><div className="shell image-story-grid"><figure><img src="/projects/warmtepomp-vlijmen.jpg" alt="Warmtepompinstallatie van Rob Braam in Vlijmen" /><figcaption>Door ons geplaatst in Vlijmen</figcaption></figure><div><p className="eyebrow"><span /> Van aanvraag tot offerte</p><h2>Een technische opname wanneer die nodig is.</h2><p>Na de eerste beoordeling bepalen we of we de offerte met de ontvangen informatie kunnen uitwerken of dat een opname op locatie nodig is. Tijdens zo&apos;n opname brengen we de bestaande installatie, warmteafgifte, mogelijke plaats van de buitenunit en groepenkast in kaart. Onze monteurs en elektricien stemmen de installatie vervolgens als één geheel af.</p><div className="story-points"><div><strong>1.</strong><span>Aanvraag, installatiegegevens en foto&apos;s beoordelen</span></div><div><strong>2.</strong><span>Zo nodig een technische opname inplannen</span></div><div><strong>3.</strong><span>Woning en installatie gericht in kaart brengen</span></div><div><strong>4.</strong><span>Advies en offerte uitwerken</span></div></div></div></div></section>

    <section className="section faq-section reveal"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow"><span /> Veelgestelde vragen</p><h2>Dit willen klanten vaak<br />eerst van ons weten.</h2></div><p>U hoeft de techniek vooraf niet zelf uit te zoeken. Stuur bij uw aanvraag vooral door wat u al weet; wij bepalen daarna welke informatie of opname nog nodig is.</p></div><div className="faq-grid"><article><h3>Kan mijn woning van het gas af?</h3><p>Dat hangt onder meer af van het warmteverlies, de isolatie, de warmteafgifte en de elektrische aansluiting. Daarom beoordelen we dit altijd per woning.</p></article><article><h3>Heb ik vloerverwarming nodig?</h3><p>Niet altijd. Ook geschikte radiatoren kunnen werken, maar de benodigde watertemperatuur en capaciteit moeten bij de woning passen. Dat beoordelen we vooraf en, wanneer nodig, tijdens een technische opname.</p></article><article><h3>Kan een warmtepomp ook koelen?</h3><p>Dat kan bij geschikte systemen en een passende afgifte-installatie. Niet iedere radiator of vloerverwarming is automatisch geschikt; in de offerte staat welke functies voor uw woning worden aangeboden.</p></article><article><h3>Hoe zit het met geluid en de buitenunit?</h3><p>Het model, het benodigde vermogen en de plaats van de buitenunit bepalen samen wat u en de buren horen. Als een opname nodig is, nemen we de mogelijke opstelplaats daarin mee.</p></article><article><h3>Moet ik zelf een elektricien regelen?</h3><p>Nee. Onze eigen elektricien kan de groepenkast uitbreiden en de juiste voeding voor de warmtepomp aanleggen.</p></article><article><h3>Kan Braam het onderhoud blijven doen?</h3><p>Ja. Voor warmtepompen van LG en Vaillant bieden we standaard onderhoud. Heeft u een ander merk, dan beoordelen we op basis van merk, model en installatie of onderhoud mogelijk is.</p></article></div></div></section>
    <ContactCTA title="Interesse in een warmtepomp?" text="Vertel ons iets over uw woning en huidige installatie. We beoordelen de aanvraag en laten weten of een technische opname nodig is. Daarna werken we het advies en de offerte uit." primaryLabel="Vraag warmtepompadvies aan" primaryHref="/offerte-aanvragen?dienst=warmtepomp" />
  </main><MobileActionBar href="/offerte-aanvragen?dienst=warmtepomp" label="Vraag advies aan" /><SiteFooter /></>;
}
