import type { Metadata } from "next";
import Link from "next/link";
import { ContactCTA } from "../components/ContactCTA";
import { MobileActionBar } from "../components/MobileActionBar";
import { PageHero } from "../components/PageHero";
import { RelatedKnowledge } from "../components/RelatedKnowledge";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";

export const metadata: Metadata = { title: "Cv-ketel installeren en onderhouden | Rob Braam", description: "Veilige plaatsing, vervanging en onderhoud van cv-ketels door een CO-VRIJ-gecertificeerd installatiebedrijf vanuit 's-Hertogenbosch, actief in Noord-Brabant en aangrenzende delen van Gelderland." };

export default function CvKetelsPage() {
  return <><SiteHeader /><main>
    <PageHero eyebrow="Cv-ketels" title="Is uw cv-ketel aan vervanging toe?" accent="Wij regelen toestel én veilige aansluiting." intro="Bij het vervangen van een cv-ketel kijken we niet alleen naar het nieuwe toestel. Ook de rookgasafvoer, luchttoevoer, gasleiding en bestaande installatie moeten veilig en goed op elkaar aansluiten. Ons gecertificeerde team verzorgt de plaatsing, controles en oplevering." image="/brand/vaillant-banner.jpg" imageAlt="Vaillant, comfort voor thuis" primaryLabel="Bespreek ketelvervanging" primaryHref="/offerte-aanvragen?dienst=cv-ketel" badge="Vier vaste ketelmerken" />
    <section className="section detail-intro reveal"><div className="shell detail-intro-grid"><div><p className="eyebrow"><span /> Vervangen, installeren en onderhouden</p><h2>Een nieuwe ketel<br />staat nooit op zichzelf.</h2></div><div><p>We bepalen welk vermogen en warmwatercomfort bij uw huishouden passen en controleren hoe de bestaande installatie is opgebouwd. In de offerte maken we duidelijk welk toestel wordt geplaatst en welke aanpassingen aan rookgasafvoer, leidingwerk of regeling nodig zijn.</p><ul className="check-list"><li>Advies over vermogen en warm water</li><li>Rookgasafvoer en luchttoevoer meegenomen</li><li>Gasleiding gecontroleerd op lekdichtheid</li><li>Oplevering met metingen en rapport</li></ul></div></div></section>

    <section className="section brand-scope-section reveal"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow"><span /> Duidelijke onderhoudsscope</p><h2>Deze cv-ketels<br />onderhouden wij.</h2></div><p>Voor onderhoud werken we uitsluitend met Intergas, Remeha, Nefit en Vaillant. Zo weet u vooraf of een onderhoudsaanvraag bij ons past.</p></div><div className="boiler-brand-grid" aria-label="Cv-ketelmerken die wij onderhouden"><figure className="boiler-brand-card boiler-brand-intergas"><div className="boiler-brand-logo"><img src="/brand/intergas-logo.svg" alt="" /></div><figcaption>Intergas</figcaption></figure><figure className="boiler-brand-card"><div className="boiler-brand-logo"><img src="/brand/remeha-logo.svg" alt="" /></div><figcaption>Remeha</figcaption></figure><figure className="boiler-brand-card"><div className="boiler-brand-logo"><img src="/brand/nefit-bosch-logo.png" alt="" /></div><figcaption>Nefit</figcaption></figure><figure className="boiler-brand-card"><div className="boiler-brand-logo"><img src="/brand/vaillant-logo.png" alt="" /></div><figcaption>Vaillant</figcaption></figure></div><div className="scope-callout"><strong>Tot en met 40 kW</strong><p>Wij onderhouden cv-ketels tot en met 40 kW in woningen en vergelijkbare kleinschalige panden. Collectieve ketelhuizen, cascadeopstellingen en grote bedrijfsinstallaties vallen buiten onze werkzaamheden. Stuur bij uw aanvraag merk, model en vermogen mee als dat bekend is.</p></div></div></section>

    <section className="certification-section reveal"><div className="shell certification-grid"><div className="certificate-visual" aria-hidden="true"><div className="shield"><span>CO</span><small>VRIJ</small></div><div className="cert-ring cert-ring-one" /><div className="cert-ring cert-ring-two" /><span className="cert-date">Verplicht sinds 01.04.2023</span></div><div className="certification-copy"><p className="eyebrow eyebrow-light"><span /> Wat het CO-stelsel voor u betekent</p><h2>Toestel, luchttoevoer en rookgasafvoer horen bij elkaar.</h2><p>Sinds 1 april 2023 mogen alleen gecertificeerde bedrijven werkzaamheden uitvoeren aan gasverbrandingsinstallaties. Dat gaat niet alleen om de cv-ketel, maar ook om de bijbehorende verbrandingsluchttoevoer en rookgasafvoer. De monteur moet aantoonbaar vakbekwaam zijn en zich kunnen legitimeren.</p><div className="certificate-proof"><span aria-hidden="true">✓</span><p><strong>Bij Braam zijn certificering en vakbekwaamheid geregeld.</strong><small>De CO-certificering en registraties lopen via CO-Keur. Onze monteurs hebben hun Vakmanschap CO via Installatiewerk Nederland behaald.</small></p></div><a className="certificate-link" href="https://www.volkshuisvestingnederland.nl/onderwerpen/verduurzamen-en-verbeteren/koolmonoxide-voorkomen" target="_blank" rel="noreferrer">Lees de officiële uitleg over het CO-stelsel <span aria-hidden="true">↗</span></a></div></div></section>

    <section className="section maintenance-choice-section reveal"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow"><span /> Veiligheid vastgelegd</p><h2>Rookgasafvoer en gasleiding<br />horen bij de controle.</h2></div><p>De regels rond werkzaamheden aan cv-ketels zijn aangescherpt. Daarom kijken we bij vervanging en onderhoud naar de complete gasverbrandingsinstallatie en leggen we de uitgevoerde controles vast.</p></div><div className="maintenance-choice-grid"><article><span className="choice-label">Bij vervanging</span><h3>Nieuwe ketel, veilige afvoer en lekdichte gasleiding</h3><p>Bij vervanging van een afvoergebonden cv-ketel wordt de bijbehorende individuele rookgasafvoer gelijktijdig vervangen. De bestaande gasleiding beproeven we op lekdichtheid. Na plaatsing stellen we de installatie in bedrijf en leggen we de controles en metingen vast.</p><ul><li>Nieuwe rookgasafvoer en passende luchttoevoer</li><li>Lekdichtheidsbeproeving van de gasleiding</li><li>Controle van werking, afstelling en rookgassen</li><li>Opleverings- en beproevingsrapport</li></ul></article><article className="maintenance-choice-contract"><span className="choice-label">Bij onderhoud</span><h3>Onderhoud, veiligheidscontrole en keuringsrapport</h3><p>Een onderhoudsbeurt bestaat uit meer dan schoonmaken. We controleren het toestel, de aansluitingen, de verbrandingsluchttoevoer en de rookgasafvoer. Ook voeren we de voorgeschreven metingen uit. Na afloop ontvangt u een rapport met de resultaten, geconstateerde afwijkingen en ons advies.</p><ul><li>Controle van beugeling, afschot, verbindingen en lekkage</li><li>Metingen van onder meer CO, O₂ en rookgastemperatuur</li><li>Controle van veilige werking en afstelling</li><li>Afwijkingen en advies vastgelegd in het rapport</li></ul></article></div><p className="maintenance-choice-note">Bij een bestaande installatie maken we onderscheid tussen een adviespunt en een onveilige situatie. Niet iedere afwijking betekent dat de complete rookgasafvoer direct moet worden vervangen, maar een advies tot aanpassing moet wel serieus worden genomen. Kan de veiligheid niet worden vastgesteld, dan is nader onderzoek of herstel nodig. Een onveilige installatie stellen we niet in bedrijf.</p></div></section>

    <section className="section process-section reveal"><div className="shell"><div className="section-heading centered-heading"><p className="eyebrow"><span /> Zo regelen we een nieuwe ketel</p><h2>U weet vooraf waar u aan toe bent.</h2></div><div className="process-grid"><article><span>01</span><div className="process-line"><i /></div><h3>We bekijken de installatie</h3><p>We bespreken uw wensen en controleren de cv-ketel, rookgasafvoer, gasleiding en bestaande aansluitingen.</p></article><article><span>02</span><div className="process-line"><i /></div><h3>U ontvangt een duidelijke offerte</h3><p>We leggen uit welk toestel past en welke werkzaamheden nodig zijn voor een veilige vervanging.</p></article><article><span>03</span><div className="process-line"><i /></div><h3>We testen en rapporteren</h3><p>Na de plaatsing beproeven we de gasleiding, stellen we de ketel in en leggen we de controles en metingen vast.</p></article></div></div></section>

    <section className="section maintenance-teaser reveal"><div className="shell maintenance-teaser-grid"><div><p className="eyebrow"><span /> Onderhoud met duidelijke afspraken</p><h2>Comfort of Comfort Plus<br />voor uw cv-ketel.</h2><p>Comfort kost € 11,58 per maand, met een jaarprijs van € 139. Comfort Plus kost € 19,92 per maand, met een jaarprijs van € 239. U kiest tussen maandelijkse automatische incasso en betaling per jaar.</p></div><div className="maintenance-card"><span>Onderhoud cv-ketel</span><strong>Vanaf € 11,58<small>/ maand</small></strong><p className="maintenance-monthly">Jaarprijs Comfort: € 139</p><ul><li>Ieder jaar een geplande controle van uw cv-ketel</li><li>Bij onderhoud: voorrijkosten en arbeidsloon inbegrepen</li><li>Bij storing: 24/7 storingsservice, voorrijkosten en arbeidsloon inbegrepen</li><li>Comfort: materiaal wordt apart berekend</li><li>Comfort Plus: materiaal binnen de onderhoudsmantel inbegrepen</li><li>Voor Intergas, Remeha, Nefit en Vaillant</li></ul><Link className="button button-primary" href="/onderhoud">Vergelijk de abonnementen <span>→</span></Link></div></div></section>
    <RelatedKnowledge service="cv-ketels" eyebrow="Handige tips over uw cv-ketel" title="Praktische uitleg voor thuis." intro="Lees wat u zelf veilig kunt controleren, zoals waterdruk, en wanneer terugkerende klachten door een monteur moeten worden onderzocht." />
    <ContactCTA title="Wilt u uw cv-ketel vervangen of onderhouden?" text="Vertel ons welk toestel u heeft en waar u hulp bij zoekt. Dan kijkt iemand uit ons team persoonlijk met u mee." primaryLabel="Vraag advies over uw cv-ketel" primaryHref="/offerte-aanvragen?dienst=cv-ketel" />
  </main><MobileActionBar href="/offerte-aanvragen?dienst=cv-ketel" label="Bespreek uw cv-ketel" /><SiteFooter /></>;
}
